# Generated by Django 4.2 on 2024-12-07 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0005_remove_worker_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supervisorcreateworker",
            name="group",
        ),
    ]
