# Generated by Django 4.2 on 2024-12-07 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0006_remove_supervisorcreateworker_group"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MainProfile",
        ),
        migrations.DeleteModel(
            name="SupervisorProfile",
        ),
        migrations.DeleteModel(
            name="WorkerProfile",
        ),
    ]
