# Generated by Django 4.2 on 2024-12-08 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("farmers", "0007_delete_mainprofile_delete_supervisorprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="role",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="workId",
        ),
    ]
